import{chromium}from'@playwright/test';import assert from'node:assert/strict';import{mkdir,writeFile}from'node:fs/promises';
const browser=await chromium.launch(),errors=[],base='http://127.0.0.1:4175';await mkdir('artifacts/inventory',{recursive:true});async function open(width,role='owner'){const p=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/__test/signin?role='+role);await p.getByText('Saved across your devices',{exact:true}).waitFor();return p}
try{const phone=await open(390);assert.equal(await phone.locator('article.item').count(),37);const current=phone.getByLabel('Current quantity: 10 Volume Developer',{exact:true}),order=phone.getByLabel('Order quantity: 10 Volume Developer',{exact:true});await current.fill('4');await current.press('Tab');await order.fill('2');await order.press('Tab');await phone.getByText('Saved across your devices',{exact:true}).waitFor();await phone.reload();await phone.getByText('Saved across your devices',{exact:true}).waitFor();assert.equal(await current.inputValue(),'4');
 const desktop=await open(1280);assert.equal(await desktop.getByLabel('Current quantity: 10 Volume Developer',{exact:true}).inputValue(),'4');await desktop.getByLabel('Notes and supplier: 10 Volume Developer',{exact:true}).click();await desktop.getByLabel('Supplier',{exact:true}).fill('SalonCentric');await desktop.getByLabel('Notes',{exact:true}).fill('Two for next delivery');await desktop.getByRole('button',{name:'Save details',exact:true}).click();await desktop.getByText('Saved across your devices',{exact:true}).waitFor();await phone.reload();await phone.getByText('SalonCentric',{exact:true}).waitFor();
 await phone.getByRole('button',{name:'Open floating calculator',exact:true}).click();await phone.getByLabel('Calculation',{exact:true}).fill('(12+6)*2');await phone.getByRole('button',{name:'Equals',exact:true}).click();assert.equal(await phone.getByLabel('Calculation',{exact:true}).inputValue(),'36');await phone.getByRole('button',{name:'Collapse calculator',exact:true}).click();await phone.getByRole('button',{name:'Open floating calculator',exact:true}).click();assert.equal(await phone.getByLabel('Calculation',{exact:true}).inputValue(),'36');await phone.getByLabel('Calculation',{exact:true}).press('Escape');
 await phone.getByRole('button',{name:'To order',exact:true}).click();assert.equal(await phone.locator('article.item').count(),1);const download=phone.waitForEvent('download');await phone.getByRole('button',{name:/Export order list/}).click();assert.ok((await download).suggestedFilename().endsWith('.csv'));
 const maintenance=await open(768,'maintenance');await maintenance.getByText(/MAINTENANCE TEST SPACE/).waitFor();assert.equal(await maintenance.getByLabel('Current quantity: 10 Volume Developer',{exact:true}).inputValue(),'');const forbidden=await maintenance.request.get(base+'/inventory/api/state');assert.equal(forbidden.status(),403);
 for(const width of[320,768,1024,1440]){await desktop.setViewportSize({width,height:900});await desktop.getByRole('button',{name:'All products',exact:true}).click();assert.ok(await desktop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);await desktop.screenshot({path:`artifacts/inventory/inventory-${width}.png`,fullPage:false})}assert.deepEqual(errors,[]);await writeFile('artifacts/inventory/results.json',JSON.stringify({passed:['37 products','cross-device saving','notes and suppliers','calculator persistence','reorder CSV','maintenance isolation','320/768/1024/1440 layouts'],errors},null,2));
}catch(e){for(const p of browser.contexts().flatMap(c=>c.pages())){console.log(await p.locator('body').innerText());await p.screenshot({path:'artifacts/inventory/failure-'+Date.now()+'.png'})}throw e}finally{await browser.close()}
